#!/bin/sh
xrandr --output DVI-D-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI-0 --mode 1920x1080 --pos 0x159 --rotate normal
~/.fehbg
xrdb ~/.Xresources 
systemctl --user import-environment DISPLAY
lxsession &
urxvtd &
dunst &
picom &
slstatus &
exec dwm
